# Generated by Django 4.2.1 on 2023-05-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_options_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1, max_length=50),
        ),
    ]
