# Generated by Django 4.2.1 on 2023-05-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'active'), ('inactive', 'inactive'), ('cal_progress', 'cal_progress'), ('decommission', 'decommission')], default='active', max_length=50, null=True),
        ),
    ]
