# Generated by Django 4.2.1 on 2023-06-07 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='asset_no',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='caltype',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='current_location',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='drawing_date',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='drawing_no',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='model_no',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='nist_no',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='ref_standard',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='retirement_date',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='serial_no',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='service_date',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='supplier_code',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='unit_of_meas',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='user_defined',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='vendor_contact',
        ),
    ]
