# Generated by Django 4.2.1 on 2023-06-07 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_remove_equipment_asset_no_remove_equipment_caltype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibration',
            name='department_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibrations', to='equipment.department'),
        ),
        migrations.AddField(
            model_name='calibration',
            name='equipment_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibrations', to='equipment.equipment'),
        ),
    ]
