# Generated by Django 4.2.1 on 2023-06-16 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_calibration_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.IntegerField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive'), ('cal_progress', 'Cal_progress'), ('decommission', 'Decommission')], null=True),
        ),
    ]
