# Generated by Django 4.2.1 on 2023-06-16 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0009_alter_equipment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive'), ('cal_progress', 'Cal_progress'), ('decommission', 'Decommission')], max_length=20, null=True),
        ),
    ]
