# Generated by Django 4.2.1 on 2023-06-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0010_alter_equipment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='due_cal',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='last_cal',
            field=models.DateField(blank=True, null=True),
        ),
    ]
